package dev.gridio.dnp3.codegen.model.enums.protocol

import dev.gridio.dnp3.codegen.model._

object FunctionCode extends EnumModel {

  override def implOrd: Boolean = true
  override def captureUnknownValues: Boolean = false

  override def render: IntRender = IntRender.Base10

  override def name: String = "FunctionCode"

  override def comments: List[String] = List("Application layer function code enumeration")

  override def values: List[EnumValue] = List(
    EnumValue("Confirm", 0, "Master sends this to an outstation to confirm the receipt of an Application Layer fragment"),
    EnumValue("Read", 1, "Outstation shall return the data specified by the objects in the request"),
    EnumValue("Write", 2, "Outstation shall store the data specified by the objects in the request"),
    EnumValue("Select", 3, "Outstation shall select (or arm) the output points specified by the objects in the request in preparation for a subsequent operate command"),
    EnumValue("Operate", 4, "Outstation shall activate the output points selected (or armed) by a previous select function code command"),
    EnumValue("DirectOperate", 5, "Outstation shall immediately actuate the output points specified by the objects in the request"),
    EnumValue("DirectOperateNoResponse", 6, "Same as DirectOperate but outstation shall not send a response"),
    EnumValue("ImmediateFreeze", 7, "Outstation shall copy the point data values specified by the objects in the request to a separate freeze buffer"),
    EnumValue("ImmediateFreezeNoResponse", 8, "Same as ImmediateFreeze but outstation shall not send a response"),
    EnumValue("FreezeClear", 9, "Outstation shall copy the point data values specified by the objects in the request into a separate freeze buffer and then clear the values"),
    EnumValue("FreezeClearNoResponse", 10, "Same as FreezeClear but outstation shall not send a response"),
    EnumValue("FreezeAtTime", 11, "Outstation shall copy the point data values specified by the objects in the request to a separate freeze buffer at the time and/or time intervals specified in a special time data information object"),
    EnumValue("FreezeAtTimeNoResponse", 12, "Same as FreezeAtTime but outstation shall not send a response"),
    EnumValue("ColdRestart", 13, "Outstation shall perform a complete reset of all hardware and software in the device"),
    EnumValue("WarmRestart", 14, "Outstation shall reset only portions of the device"),
    EnumValue("InitializeData", 15, "Obsolete-Do not use for new designs"),
    EnumValue("InitializeApplication", 16, "Outstation shall place the applications specified by the objects in the request into the ready to run state"),
    EnumValue("StartApplication", 17, "Outstation shall start running the applications specified by the objects in the request"),
    EnumValue("StopApplication", 18, "Outstation shall stop running the applications specified by the objects in the request"),
    EnumValue("SaveConfiguration", 19, "This code is deprecated-Do not use for new designs"),
    EnumValue("EnableUnsolicited", 20, "Enables outstation to initiate unsolicited responses from points specified by the objects in the request"),
    EnumValue("DisableUnsolicited", 21, "Prevents outstation from initiating unsolicited responses from points specified by the objects in the request"),
    EnumValue("AssignClass", 22, "Outstation shall assign the events generated by the points specified by the objects in the request to one of the classes"),
    EnumValue("DelayMeasure", 23, "Outstation shall report the time it takes to process and initiate the transmission of its response"),
    EnumValue("RecordCurrentTime", 24, "Outstation shall save the time when the last octet of this message is received"),
    EnumValue("OpenFile", 25, "Outstation shall open a file"),
    EnumValue("CloseFile", 26, "Outstation shall close a file"),
    EnumValue("DeleteFile", 27, "Outstation shall delete a file"),
    EnumValue("GetFileInfo", 28, "Outstation shall retrieve information about a file"),
    EnumValue("AuthenticateFile", 29, "Outstation shall return a file authentication key"),
    EnumValue("AbortFile", 30, "Outstation shall abort a file transfer operation"),
    EnumValue("Response", 129, "Master shall interpret this fragment as an Application Layer response to an ApplicationLayer request"),
    EnumValue("UnsolicitedResponse", 130, "Master shall interpret this fragment as an unsolicited response that was not prompted by an explicit request"),
  )

}
